/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HealthzGet200Response {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "time")]
    pub time: chrono::DateTime<chrono::FixedOffset>,
}

impl HealthzGet200Response {
    pub fn new(status: Status, time: chrono::DateTime<chrono::FixedOffset>) -> HealthzGet200Response {
        HealthzGet200Response {
            status,
            time,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "ok")]
    Ok,
}

impl Default for Status {
    fn default() -> Status {
        Self::Ok
    }
}

