/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1SendPostRequest {
    #[serde(rename = "from")]
    pub from: String,
    #[serde(rename = "to")]
    pub to: Vec<String>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<String>>,
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<String>>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// Plain-text body. Required if `html` is absent.
    #[serde(rename = "text", skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
    /// HTML body. Required if `text` is absent.
    #[serde(rename = "html", skip_serializing_if = "Option::is_none")]
    pub html: Option<String>,
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    /// Mark as opt-in/broadcast: skips suppressed recipients and adds a managed one-click List-Unsubscribe header.
    #[serde(rename = "unsubscribe", skip_serializing_if = "Option::is_none")]
    pub unsubscribe: Option<bool>,
    /// Render subject/text/html from a stored template (GET /v1/templates). Mutually exclusive with inline subject/text/html.
    #[serde(rename = "template_id", skip_serializing_if = "Option::is_none")]
    pub template_id: Option<uuid::Uuid>,
    /// Values substituted into the template's {{variable}} placeholders.
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<std::collections::HashMap<String, String>>,
    /// Schedule delivery for a future RFC3339 time (≤ 30 days out). Omit or past = send now. Cancel with DELETE /v1/messages/{id} while scheduled.
    #[serde(rename = "send_at", skip_serializing_if = "Option::is_none")]
    pub send_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::V1SendPostRequestAttachmentsInner>>,
}

impl V1SendPostRequest {
    pub fn new(from: String, to: Vec<String>) -> V1SendPostRequest {
        V1SendPostRequest {
            from,
            to,
            cc: None,
            bcc: None,
            subject: None,
            text: None,
            html: None,
            headers: None,
            unsubscribe: None,
            template_id: None,
            variables: None,
            send_at: None,
            attachments: None,
        }
    }
}

