/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1ApiKeysPost201Response {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    /// 8-char public prefix; safe to store and display.
    #[serde(rename = "prefix")]
    pub prefix: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "last_used_at", skip_serializing_if = "Option::is_none")]
    pub last_used_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "revoked_at", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// The full `lk_live_<prefix>_<secret>` token. Shown ONCE.
    #[serde(rename = "secret")]
    pub secret: String,
}

impl V1ApiKeysPost201Response {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, prefix: String, scopes: Vec<String>, label: String, created_at: chrono::DateTime<chrono::FixedOffset>, secret: String) -> V1ApiKeysPost201Response {
        V1ApiKeysPost201Response {
            id,
            tenant_id,
            prefix,
            scopes,
            label,
            last_used_at: None,
            revoked_at: None,
            created_at,
            secret,
        }
    }
}

