/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V1MailboxesEmailExportPost201Response {
    /// Relative download URL. Caller appends to the API host.
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "expires_at")]
    pub expires_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "format")]
    pub format: Format,
}

impl V1MailboxesEmailExportPost201Response {
    pub fn new(url: String, expires_at: chrono::DateTime<chrono::FixedOffset>, format: Format) -> V1MailboxesEmailExportPost201Response {
        V1MailboxesEmailExportPost201Response {
            url,
            expires_at,
            format,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Format {
    #[serde(rename = "mbox")]
    Mbox,
}

impl Default for Format {
    fn default() -> Format {
        Self::Mbox
    }
}

