/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddOn {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "price_naira")]
    pub price_naira: i32,
    #[serde(rename = "pricing_model")]
    pub pricing_model: String,
    #[serde(rename = "active")]
    pub active: bool,
}

impl AddOn {
    pub fn new(name: String, display_name: String, description: String, price_naira: i32, pricing_model: String, active: bool) -> AddOn {
        AddOn {
            name,
            display_name,
            description,
            price_naira,
            pricing_model,
            active,
        }
    }
}

