/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdminFull {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "last_login_at", skip_serializing_if = "Option::is_none")]
    pub last_login_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "disabled")]
    pub disabled: bool,
    #[serde(rename = "disabled_at", skip_serializing_if = "Option::is_none")]
    pub disabled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Present ONLY on POST response when lockally generated the password. Shown once.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl AdminFull {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, email: String, role: Role, created_at: chrono::DateTime<chrono::FixedOffset>, disabled: bool) -> AdminFull {
        AdminFull {
            id,
            tenant_id,
            email,
            display_name: None,
            role,
            last_login_at: None,
            created_at,
            disabled,
            disabled_at: None,
            password: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "viewer")]
    Viewer,
}

impl Default for Role {
    fn default() -> Role {
        Self::Admin
    }
}

