/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BillingStatus {
    #[serde(rename = "plan")]
    pub plan: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "rate_cap_per_min")]
    pub rate_cap_per_min: i32,
    #[serde(rename = "monthly_included_sends")]
    pub monthly_included_sends: i32,
    #[serde(rename = "msgs_this_period")]
    pub msgs_this_period: i32,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "price_naira_per_seat")]
    pub price_naira_per_seat: i32,
    #[serde(rename = "subscribed_at", skip_serializing_if = "Option::is_none")]
    pub subscribed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "current_period_end", skip_serializing_if = "Option::is_none")]
    pub current_period_end: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "send_units_balance")]
    pub send_units_balance: i32,
    #[serde(rename = "send_units_next_expiry", skip_serializing_if = "Option::is_none")]
    pub send_units_next_expiry: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "unit_bundles")]
    pub unit_bundles: Vec<models::UnitBundle>,
    #[serde(rename = "catalog")]
    pub catalog: Vec<models::PlanCatalogEntry>,
}

impl BillingStatus {
    pub fn new(plan: String, display_name: String, mode: Mode, rate_cap_per_min: i32, monthly_included_sends: i32, msgs_this_period: i32, status: Status, price_naira_per_seat: i32, created_at: chrono::DateTime<chrono::FixedOffset>, send_units_balance: i32, unit_bundles: Vec<models::UnitBundle>, catalog: Vec<models::PlanCatalogEntry>) -> BillingStatus {
        BillingStatus {
            plan,
            display_name,
            mode,
            rate_cap_per_min,
            monthly_included_sends,
            msgs_this_period,
            status,
            price_naira_per_seat,
            subscribed_at: None,
            current_period_end: None,
            created_at,
            send_units_balance,
            send_units_next_expiry: None,
            unit_bundles,
            catalog,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "api")]
    Api,
    #[serde(rename = "business")]
    Business,
    #[serde(rename = "both")]
    Both,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::Api
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

