/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUnitsCheckoutRequest {
    #[serde(rename = "bundle")]
    pub bundle: Bundle,
}

impl CreateUnitsCheckoutRequest {
    pub fn new(bundle: Bundle) -> CreateUnitsCheckoutRequest {
        CreateUnitsCheckoutRequest {
            bundle,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Bundle {
    #[serde(rename = "1k")]
    Variant1k,
    #[serde(rename = "10k")]
    Variant10k,
    #[serde(rename = "50k")]
    Variant50k,
    #[serde(rename = "100k")]
    Variant100k,
    #[serde(rename = "1pkt")]
    Variant1pkt,
    #[serde(rename = "5pkt")]
    Variant5pkt,
    #[serde(rename = "10pkt")]
    Variant10pkt,
    #[serde(rename = "20pkt")]
    Variant20pkt,
}

impl Default for Bundle {
    fn default() -> Bundle {
        Self::Variant1k
    }
}

