/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectoryPermissions {
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "contact_view_access")]
    pub contact_view_access: ContactViewAccess,
    #[serde(rename = "contact_edit_access")]
    pub contact_edit_access: ContactEditAccess,
    #[serde(rename = "list_manage_access")]
    pub list_manage_access: ListManageAccess,
    #[serde(rename = "external_sharing")]
    pub external_sharing: ExternalSharing,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl DirectoryPermissions {
    pub fn new(tenant_id: uuid::Uuid, contact_view_access: ContactViewAccess, contact_edit_access: ContactEditAccess, list_manage_access: ListManageAccess, external_sharing: ExternalSharing) -> DirectoryPermissions {
        DirectoryPermissions {
            tenant_id,
            contact_view_access,
            contact_edit_access,
            list_manage_access,
            external_sharing,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContactViewAccess {
    #[serde(rename = "all_users")]
    AllUsers,
    #[serde(rename = "same_department")]
    SameDepartment,
    #[serde(rename = "admins_only")]
    AdminsOnly,
}

impl Default for ContactViewAccess {
    fn default() -> ContactViewAccess {
        Self::AllUsers
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContactEditAccess {
    #[serde(rename = "all_users")]
    AllUsers,
    #[serde(rename = "admins_only")]
    AdminsOnly,
}

impl Default for ContactEditAccess {
    fn default() -> ContactEditAccess {
        Self::AllUsers
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ListManageAccess {
    #[serde(rename = "all_users")]
    AllUsers,
    #[serde(rename = "list_owners")]
    ListOwners,
    #[serde(rename = "admins_only")]
    AdminsOnly,
}

impl Default for ListManageAccess {
    fn default() -> ListManageAccess {
        Self::AllUsers
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ExternalSharing {
    #[serde(rename = "allowed")]
    Allowed,
    #[serde(rename = "restricted")]
    Restricted,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for ExternalSharing {
    fn default() -> ExternalSharing {
        Self::Allowed
    }
}

