/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DnsRecord {
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "ttl")]
    pub ttl: i32,
    /// MX records only.
    #[serde(rename = "priority", skip_serializing_if = "Option::is_none")]
    pub priority: Option<i32>,
    #[serde(rename = "purpose")]
    pub purpose: Purpose,
}

impl DnsRecord {
    pub fn new(r#type: Type, name: String, value: String, ttl: i32, purpose: Purpose) -> DnsRecord {
        DnsRecord {
            r#type,
            name,
            value,
            ttl,
            priority: None,
            purpose,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TXT")]
    Txt,
    #[serde(rename = "MX")]
    Mx,
}

impl Default for Type {
    fn default() -> Type {
        Self::Txt
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Purpose {
    #[serde(rename = "verification")]
    Verification,
    #[serde(rename = "spf")]
    Spf,
    #[serde(rename = "dkim")]
    Dkim,
    #[serde(rename = "mx-primary")]
    MxPrimary,
    #[serde(rename = "mx-backup")]
    MxBackup,
    #[serde(rename = "dmarc")]
    Dmarc,
}

impl Default for Purpose {
    fn default() -> Purpose {
        Self::Verification
    }
}

