/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GalSettings {
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "gal_enabled")]
    pub gal_enabled: bool,
    #[serde(rename = "hide_from_directory")]
    pub hide_from_directory: bool,
    #[serde(rename = "department_grouping")]
    pub department_grouping: bool,
    #[serde(rename = "search_visibility")]
    pub search_visibility: SearchVisibility,
    #[serde(rename = "include_external_contacts")]
    pub include_external_contacts: bool,
    #[serde(rename = "last_index_rebuilt_at", skip_serializing_if = "Option::is_none")]
    pub last_index_rebuilt_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "last_synced_at", skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GalSettings {
    pub fn new(tenant_id: uuid::Uuid, gal_enabled: bool, hide_from_directory: bool, department_grouping: bool, search_visibility: SearchVisibility, include_external_contacts: bool) -> GalSettings {
        GalSettings {
            tenant_id,
            gal_enabled,
            hide_from_directory,
            department_grouping,
            search_visibility,
            include_external_contacts,
            last_index_rebuilt_at: None,
            last_synced_at: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchVisibility {
    #[serde(rename = "all_users")]
    AllUsers,
    #[serde(rename = "same_department")]
    SameDepartment,
    #[serde(rename = "admins_only")]
    AdminsOnly,
}

impl Default for SearchVisibility {
    fn default() -> SearchVisibility {
        Self::AllUsers
    }
}

