/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAuditSummary200Response {
    #[serde(rename = "admin_actions_today", skip_serializing_if = "Option::is_none")]
    pub admin_actions_today: Option<i32>,
    #[serde(rename = "recent_logins", skip_serializing_if = "Option::is_none")]
    pub recent_logins: Option<Vec<models::AuditEvent>>,
    #[serde(rename = "recent_exports", skip_serializing_if = "Option::is_none")]
    pub recent_exports: Option<Vec<models::AuditEvent>>,
    #[serde(rename = "deleted_mailboxes", skip_serializing_if = "Option::is_none")]
    pub deleted_mailboxes: Option<Vec<models::AuditEvent>>,
    #[serde(rename = "generated_at", skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetAuditSummary200Response {
    pub fn new() -> GetAuditSummary200Response {
        GetAuditSummary200Response {
            admin_actions_today: None,
            recent_logins: None,
            recent_exports: None,
            deleted_mailboxes: None,
            generated_at: None,
        }
    }
}

