/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIntegrationsSummary200Response {
    #[serde(rename = "api_requests_today", skip_serializing_if = "Option::is_none")]
    pub api_requests_today: Option<i32>,
    #[serde(rename = "active_api_keys", skip_serializing_if = "Option::is_none")]
    pub active_api_keys: Option<i32>,
    #[serde(rename = "api_keys", skip_serializing_if = "Option::is_none")]
    pub api_keys: Option<Vec<models::GetIntegrationsSummary200ResponseApiKeysInner>>,
    #[serde(rename = "webhook_failures", skip_serializing_if = "Option::is_none")]
    pub webhook_failures: Option<i32>,
    #[serde(rename = "webhooks_total", skip_serializing_if = "Option::is_none")]
    pub webhooks_total: Option<i32>,
    #[serde(rename = "webhooks", skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<Vec<models::GetIntegrationsSummary200ResponseWebhooksInner>>,
    #[serde(rename = "generated_at", skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetIntegrationsSummary200Response {
    pub fn new() -> GetIntegrationsSummary200Response {
        GetIntegrationsSummary200Response {
            api_requests_today: None,
            active_api_keys: None,
            api_keys: None,
            webhook_failures: None,
            webhooks_total: None,
            webhooks: None,
            generated_at: None,
        }
    }
}

