/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetIpAssignment200Response {
    #[serde(rename = "pool_name", skip_serializing_if = "Option::is_none")]
    pub pool_name: Option<String>,
    #[serde(rename = "pool_kind", skip_serializing_if = "Option::is_none")]
    pub pool_kind: Option<String>,
    #[serde(rename = "dedicated_ip", skip_serializing_if = "Option::is_none")]
    pub dedicated_ip: Option<String>,
    #[serde(rename = "assigned_at", skip_serializing_if = "Option::is_none")]
    pub assigned_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl GetIpAssignment200Response {
    pub fn new() -> GetIpAssignment200Response {
        GetIpAssignment200Response {
            pool_name: None,
            pool_kind: None,
            dedicated_ip: None,
            assigned_at: None,
            reason: None,
        }
    }
}

