/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCalendarSecurity200Response {
    #[serde(rename = "total_calendars", skip_serializing_if = "Option::is_none")]
    pub total_calendars: Option<i32>,
    #[serde(rename = "public_calendars", skip_serializing_if = "Option::is_none")]
    pub public_calendars: Option<i32>,
    #[serde(rename = "private_calendars", skip_serializing_if = "Option::is_none")]
    pub private_calendars: Option<i32>,
    #[serde(rename = "total_members", skip_serializing_if = "Option::is_none")]
    pub total_members: Option<i32>,
    #[serde(rename = "delegated_access", skip_serializing_if = "Option::is_none")]
    pub delegated_access: Option<Vec<models::GetCalendarSecurity200ResponseDelegatedAccessInner>>,
    #[serde(rename = "public_calendar_list", skip_serializing_if = "Option::is_none")]
    pub public_calendar_list: Option<Vec<models::GetCalendarSecurity200ResponsePublicCalendarListInner>>,
    #[serde(rename = "alerts", skip_serializing_if = "Option::is_none")]
    pub alerts: Option<Vec<models::GetCalendarSecurity200ResponseAlertsInner>>,
    #[serde(rename = "external_sharing", skip_serializing_if = "Option::is_none")]
    pub external_sharing: Option<Box<models::GetCalendarSecurity200ResponseExternalSharing>>,
}

impl GetCalendarSecurity200Response {
    pub fn new() -> GetCalendarSecurity200Response {
        GetCalendarSecurity200Response {
            total_calendars: None,
            public_calendars: None,
            private_calendars: None,
            total_members: None,
            delegated_access: None,
            public_calendar_list: None,
            alerts: None,
            external_sharing: None,
        }
    }
}

