/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCalendarSecurity200ResponseExternalSharing {
    #[serde(rename = "invites_allowed", skip_serializing_if = "Option::is_none")]
    pub invites_allowed: Option<bool>,
    #[serde(rename = "sharing_allowed", skip_serializing_if = "Option::is_none")]
    pub sharing_allowed: Option<bool>,
    #[serde(rename = "public_links", skip_serializing_if = "Option::is_none")]
    pub public_links: Option<bool>,
}

impl GetCalendarSecurity200ResponseExternalSharing {
    pub fn new() -> GetCalendarSecurity200ResponseExternalSharing {
        GetCalendarSecurity200ResponseExternalSharing {
            invites_allowed: None,
            sharing_allowed: None,
            public_links: None,
        }
    }
}

