/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStorage200Response {
    #[serde(rename = "total_bytes", skip_serializing_if = "Option::is_none")]
    pub total_bytes: Option<i64>,
    #[serde(rename = "alloc_bytes", skip_serializing_if = "Option::is_none")]
    pub alloc_bytes: Option<i64>,
    #[serde(rename = "per_seat_bytes", skip_serializing_if = "Option::is_none")]
    pub per_seat_bytes: Option<i64>,
    #[serde(rename = "top_mailboxes", skip_serializing_if = "Option::is_none")]
    pub top_mailboxes: Option<Vec<models::GetStorage200ResponseTopMailboxesInner>>,
    #[serde(rename = "top_messages", skip_serializing_if = "Option::is_none")]
    pub top_messages: Option<Vec<models::GetStorage200ResponseTopMessagesInner>>,
    #[serde(rename = "generated_at", skip_serializing_if = "Option::is_none")]
    pub generated_at: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl GetStorage200Response {
    pub fn new() -> GetStorage200Response {
        GetStorage200Response {
            total_bytes: None,
            alloc_bytes: None,
            per_seat_bytes: None,
            top_mailboxes: None,
            top_messages: None,
            generated_at: None,
        }
    }
}

