/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetDirectoryStats200Response {
    #[serde(rename = "total_contacts", skip_serializing_if = "Option::is_none")]
    pub total_contacts: Option<i32>,
    #[serde(rename = "internal_users", skip_serializing_if = "Option::is_none")]
    pub internal_users: Option<i32>,
    #[serde(rename = "external_contacts", skip_serializing_if = "Option::is_none")]
    pub external_contacts: Option<i32>,
    #[serde(rename = "synced_contacts", skip_serializing_if = "Option::is_none")]
    pub synced_contacts: Option<i32>,
    #[serde(rename = "shared_lists", skip_serializing_if = "Option::is_none")]
    pub shared_lists: Option<i32>,
    #[serde(rename = "directory_groups", skip_serializing_if = "Option::is_none")]
    pub directory_groups: Option<i32>,
}

impl GetDirectoryStats200Response {
    pub fn new() -> GetDirectoryStats200Response {
        GetDirectoryStats200Response {
            total_contacts: None,
            internal_users: None,
            external_contacts: None,
            synced_contacts: None,
            shared_lists: None,
            directory_groups: None,
        }
    }
}

