/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Mailbox {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "domain_id")]
    pub domain_id: uuid::Uuid,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "quota_bytes")]
    pub quota_bytes: i64,
    #[serde(rename = "disabled")]
    pub disabled: bool,
    #[serde(rename = "disabled_at", skip_serializing_if = "Option::is_none")]
    pub disabled_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "soft_deleted_at", skip_serializing_if = "Option::is_none")]
    pub soft_deleted_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "hard_delete_after", skip_serializing_if = "Option::is_none")]
    pub hard_delete_after: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// ONLY present on POST response when lockally generated the password. Shown once.
    #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
    pub password: Option<String>,
}

impl Mailbox {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, domain_id: uuid::Uuid, email: String, quota_bytes: i64, disabled: bool, created_at: chrono::DateTime<chrono::FixedOffset>) -> Mailbox {
        Mailbox {
            id,
            tenant_id,
            domain_id,
            email,
            quota_bytes,
            disabled,
            disabled_at: None,
            soft_deleted_at: None,
            hard_delete_after: None,
            created_at,
            password: None,
        }
    }
}

