/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Message {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    /// RFC 5322 Message-ID header, including angle brackets.
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "sender")]
    pub sender: String,
    #[serde(rename = "recipients")]
    pub recipients: Vec<String>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "queued_at")]
    pub queued_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "bounce_reason", skip_serializing_if = "Option::is_none")]
    pub bounce_reason: Option<String>,
    #[serde(rename = "size_bytes", skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i32>,
}

impl Message {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, message_id: String, sender: String, recipients: Vec<String>, status: Status, queued_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Message {
        Message {
            id,
            tenant_id,
            message_id,
            sender,
            recipients,
            subject: None,
            status,
            queued_at,
            updated_at,
            bounce_reason: None,
            size_bytes: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "sending")]
    Sending,
    #[serde(rename = "delivered")]
    Delivered,
    #[serde(rename = "bounced")]
    Bounced,
    #[serde(rename = "deferred")]
    Deferred,
    #[serde(rename = "complaint")]
    Complaint,
}

impl Default for Status {
    fn default() -> Status {
        Self::Queued
    }
}

