/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrationEvent {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "migration_id")]
    pub migration_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "mailbox_id", skip_serializing_if = "Option::is_none")]
    pub mailbox_id: Option<uuid::Uuid>,
    #[serde(rename = "event_type")]
    pub event_type: String,
    #[serde(rename = "actor")]
    pub actor: String,
    #[serde(rename = "old_status", skip_serializing_if = "Option::is_none")]
    pub old_status: Option<String>,
    #[serde(rename = "new_status", skip_serializing_if = "Option::is_none")]
    pub new_status: Option<String>,
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl MigrationEvent {
    pub fn new(id: uuid::Uuid, migration_id: uuid::Uuid, tenant_id: uuid::Uuid, event_type: String, actor: String, created_at: chrono::DateTime<chrono::FixedOffset>) -> MigrationEvent {
        MigrationEvent {
            id,
            migration_id,
            tenant_id,
            mailbox_id: None,
            event_type,
            actor,
            old_status: None,
            new_status: None,
            detail: None,
            created_at,
        }
    }
}

