/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrationProgress {
    #[serde(rename = "migration_id")]
    pub migration_id: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "total_mailboxes")]
    pub total_mailboxes: i32,
    #[serde(rename = "completed_mailboxes")]
    pub completed_mailboxes: i32,
    #[serde(rename = "failed_mailboxes")]
    pub failed_mailboxes: i32,
    #[serde(rename = "total_messages")]
    pub total_messages: i32,
    #[serde(rename = "synced_messages")]
    pub synced_messages: i32,
    #[serde(rename = "failed_messages")]
    pub failed_messages: i32,
    #[serde(rename = "percent_complete")]
    pub percent_complete: f64,
    #[serde(rename = "mailboxes")]
    pub mailboxes: Vec<models::MigrationProgressMailboxesInner>,
}

impl MigrationProgress {
    pub fn new(migration_id: uuid::Uuid, status: String, total_mailboxes: i32, completed_mailboxes: i32, failed_mailboxes: i32, total_messages: i32, synced_messages: i32, failed_messages: i32, percent_complete: f64, mailboxes: Vec<models::MigrationProgressMailboxesInner>) -> MigrationProgress {
        MigrationProgress {
            migration_id,
            status,
            total_mailboxes,
            completed_mailboxes,
            failed_mailboxes,
            total_messages,
            synced_messages,
            failed_messages,
            percent_complete,
            mailboxes,
        }
    }
}

