/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MigrationMailbox {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "migration_id")]
    pub migration_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "source_email")]
    pub source_email: String,
    #[serde(rename = "dest_email", skip_serializing_if = "Option::is_none")]
    pub dest_email: Option<String>,
    #[serde(rename = "dest_mailbox_id", skip_serializing_if = "Option::is_none")]
    pub dest_mailbox_id: Option<uuid::Uuid>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "source_message_count", skip_serializing_if = "Option::is_none")]
    pub source_message_count: Option<i32>,
    #[serde(rename = "synced_message_count")]
    pub synced_message_count: i32,
    #[serde(rename = "failed_message_count")]
    pub failed_message_count: i32,
    #[serde(rename = "source_size_bytes", skip_serializing_if = "Option::is_none")]
    pub source_size_bytes: Option<i64>,
    #[serde(rename = "synced_size_bytes", skip_serializing_if = "Option::is_none")]
    pub synced_size_bytes: Option<i64>,
    #[serde(rename = "last_synced_uid", skip_serializing_if = "Option::is_none")]
    pub last_synced_uid: Option<String>,
    #[serde(rename = "last_synced_at", skip_serializing_if = "Option::is_none")]
    pub last_synced_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl MigrationMailbox {
    pub fn new(id: uuid::Uuid, migration_id: uuid::Uuid, tenant_id: uuid::Uuid, source_email: String, status: String, synced_message_count: i32, failed_message_count: i32, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> MigrationMailbox {
        MigrationMailbox {
            id,
            migration_id,
            tenant_id,
            source_email,
            dest_email: None,
            dest_mailbox_id: None,
            status,
            source_message_count: None,
            synced_message_count,
            failed_message_count,
            source_size_bytes: None,
            synced_size_bytes: None,
            last_synced_uid: None,
            last_synced_at: None,
            error_message: None,
            started_at: None,
            completed_at: None,
            created_at,
            updated_at,
        }
    }
}

