/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Migration {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "credential_id")]
    pub credential_id: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "source_provider")]
    pub source_provider: String,
    #[serde(rename = "source_summary", skip_serializing_if = "Option::is_none")]
    pub source_summary: Option<String>,
    #[serde(rename = "settings", skip_serializing_if = "Option::is_none")]
    pub settings: Option<Box<models::MigrationSettings>>,
    #[serde(rename = "error_message", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "started_at", skip_serializing_if = "Option::is_none")]
    pub started_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "completed_at", skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "mailbox_count")]
    pub mailbox_count: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl Migration {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, credential_id: uuid::Uuid, name: String, status: Status, source_provider: String, mailbox_count: i32, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> Migration {
        Migration {
            id,
            tenant_id,
            credential_id,
            name,
            status,
            source_provider,
            source_summary: None,
            settings: None,
            error_message: None,
            started_at: None,
            completed_at: None,
            mailbox_count,
            created_at,
            updated_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "discovering")]
    Discovering,
    #[serde(rename = "discovered")]
    Discovered,
    #[serde(rename = "mapped")]
    Mapped,
    #[serde(rename = "pilot_running")]
    PilotRunning,
    #[serde(rename = "pilot_complete")]
    PilotComplete,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "staged")]
    Staged,
    #[serde(rename = "cutover_pending")]
    CutoverPending,
    #[serde(rename = "final_syncing")]
    FinalSyncing,
    #[serde(rename = "validating")]
    Validating,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "cancelled")]
    Cancelled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Draft
    }
}

