/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SharedMember {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "mailbox_id")]
    pub mailbox_id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "member_email")]
    pub member_email: String,
    #[serde(rename = "role")]
    pub role: Role,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
}

impl SharedMember {
    pub fn new(id: uuid::Uuid, mailbox_id: uuid::Uuid, tenant_id: uuid::Uuid, member_email: String, role: Role, created_at: chrono::DateTime<chrono::FixedOffset>) -> SharedMember {
        SharedMember {
            id,
            mailbox_id,
            tenant_id,
            member_email,
            role,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "manager")]
    Manager,
    #[serde(rename = "member")]
    Member,
}

impl Default for Role {
    fn default() -> Role {
        Self::Manager
    }
}

