/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGalSettingsRequest {
    #[serde(rename = "gal_enabled", skip_serializing_if = "Option::is_none")]
    pub gal_enabled: Option<bool>,
    #[serde(rename = "hide_from_directory", skip_serializing_if = "Option::is_none")]
    pub hide_from_directory: Option<bool>,
    #[serde(rename = "department_grouping", skip_serializing_if = "Option::is_none")]
    pub department_grouping: Option<bool>,
    #[serde(rename = "search_visibility", skip_serializing_if = "Option::is_none")]
    pub search_visibility: Option<SearchVisibility>,
    #[serde(rename = "include_external_contacts", skip_serializing_if = "Option::is_none")]
    pub include_external_contacts: Option<bool>,
}

impl UpdateGalSettingsRequest {
    pub fn new() -> UpdateGalSettingsRequest {
        UpdateGalSettingsRequest {
            gal_enabled: None,
            hide_from_directory: None,
            department_grouping: None,
            search_visibility: None,
            include_external_contacts: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SearchVisibility {
    #[serde(rename = "all_users")]
    AllUsers,
    #[serde(rename = "same_department")]
    SameDepartment,
    #[serde(rename = "admins_only")]
    AdminsOnly,
}

impl Default for SearchVisibility {
    fn default() -> SearchVisibility {
        Self::AllUsers
    }
}

