/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateCalendarPoliciesRequest {
    #[serde(rename = "max_meeting_duration_mins", skip_serializing_if = "Option::is_none")]
    pub max_meeting_duration_mins: Option<u32>,
    #[serde(rename = "working_hours_start", skip_serializing_if = "Option::is_none")]
    pub working_hours_start: Option<String>,
    #[serde(rename = "working_hours_end", skip_serializing_if = "Option::is_none")]
    pub working_hours_end: Option<String>,
    #[serde(rename = "booking_window_days", skip_serializing_if = "Option::is_none")]
    pub booking_window_days: Option<u32>,
    #[serde(rename = "recurring_meeting_limit", skip_serializing_if = "Option::is_none")]
    pub recurring_meeting_limit: Option<u32>,
    #[serde(rename = "resource_approval_mode", skip_serializing_if = "Option::is_none")]
    pub resource_approval_mode: Option<ResourceApprovalMode>,
    #[serde(rename = "external_invites_allowed", skip_serializing_if = "Option::is_none")]
    pub external_invites_allowed: Option<bool>,
    #[serde(rename = "external_sharing_allowed", skip_serializing_if = "Option::is_none")]
    pub external_sharing_allowed: Option<bool>,
    #[serde(rename = "public_links_enabled", skip_serializing_if = "Option::is_none")]
    pub public_links_enabled: Option<bool>,
}

impl UpdateCalendarPoliciesRequest {
    pub fn new() -> UpdateCalendarPoliciesRequest {
        UpdateCalendarPoliciesRequest {
            max_meeting_duration_mins: None,
            working_hours_start: None,
            working_hours_end: None,
            booking_window_days: None,
            recurring_meeting_limit: None,
            resource_approval_mode: None,
            external_invites_allowed: None,
            external_sharing_allowed: None,
            public_links_enabled: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResourceApprovalMode {
    #[serde(rename = "auto_approve")]
    AutoApprove,
    #[serde(rename = "require_approval")]
    RequireApproval,
    #[serde(rename = "restricted")]
    Restricted,
}

impl Default for ResourceApprovalMode {
    fn default() -> ResourceApprovalMode {
        Self::AutoApprove
    }
}

