/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VacationResponder {
    #[serde(rename = "mailbox_email")]
    pub mailbox_email: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "params")]
    pub params: Box<models::VacationParams>,
    /// Pre-rendered Sieve script (RFC 5230).
    #[serde(rename = "script")]
    pub script: String,
    /// Null = stored on lockally but not yet pushed to the mail server.
    #[serde(rename = "synced_at", skip_serializing_if = "Option::is_none")]
    pub synced_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    #[serde(rename = "updated_at")]
    pub updated_at: chrono::DateTime<chrono::FixedOffset>,
}

impl VacationResponder {
    pub fn new(mailbox_email: String, enabled: bool, params: models::VacationParams, script: String, created_at: chrono::DateTime<chrono::FixedOffset>, updated_at: chrono::DateTime<chrono::FixedOffset>) -> VacationResponder {
        VacationResponder {
            mailbox_email,
            enabled,
            params: Box::new(params),
            script,
            synced_at: None,
            created_at,
            updated_at,
        }
    }
}

