/*
 * lockally control plane
 *
 * The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@lockally.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Webhook {
    #[serde(rename = "id")]
    pub id: uuid::Uuid,
    #[serde(rename = "tenant_id")]
    pub tenant_id: uuid::Uuid,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "events")]
    pub events: Vec<String>,
    #[serde(rename = "paused")]
    pub paused: bool,
    #[serde(rename = "paused_at", skip_serializing_if = "Option::is_none")]
    pub paused_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "last_success_at", skip_serializing_if = "Option::is_none")]
    pub last_success_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "last_failure_at", skip_serializing_if = "Option::is_none")]
    pub last_failure_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "consecutive_failures")]
    pub consecutive_failures: i32,
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.
    #[serde(rename = "signing_secret", skip_serializing_if = "Option::is_none")]
    pub signing_secret: Option<String>,
}

impl Webhook {
    pub fn new(id: uuid::Uuid, tenant_id: uuid::Uuid, url: String, events: Vec<String>, paused: bool, consecutive_failures: i32, created_at: chrono::DateTime<chrono::FixedOffset>) -> Webhook {
        Webhook {
            id,
            tenant_id,
            url,
            events,
            paused,
            paused_at: None,
            last_success_at: None,
            last_failure_at: None,
            consecutive_failures,
            created_at,
            signing_secret: None,
        }
    }
}

